name: 'Merge'
description: 'Pushing to GitHub repository local changes'
branding:
  icon: upload-cloud
  color: green
inputs:
  directory:
    description: 'Directory to change to before pushing.'
    required: false
    default: '.'
  email:
    description: 'Email to use on the git config'
    required: true
runs:
  using: 'node12'
  main: 'deploy.js'