on:
  push:
    branches: master

jobs:
  merge_job:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
    - uses: actions/checkout@v1
    - name: Uncomment dist folder on gitignore file
      run: sed -i 's/^\/dist.*/#\/dist/g' .gitignore
    - name: Compiles and deploy
      uses: ./.github/actions/deploy
      with:
        email: "${{secrets.EMAIL}}"
