on:
  push:
    branches: master

jobs:
  merge_job:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
    - uses: actions/checkout@v1
    - name: Get commit message
      id: commit
      run: echo ::set-output name=commit::$(git log -1 --pretty=%B)
    - name: Uncomment dist folder on gitignore file
      run: |
        git checkout gh-pages
        sed -i 's/^\/dist.*/#\/dist/g' .gitignore
    - name: Compiles and deploy
      uses: ./.github/actions/deploy
      with:
        email: "${{secrets.EMAIL}}"
        commit: "${{ steps.commit.outputs.commit }}"
